name: Run Playwright Tests and Email Report

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1-6'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest #windows-latest #macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Zip HTML Report
      run: |
          zip -r report.zip playwright-report

    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.your-email-provider.com
          server_port: 587
          username: 'satztesting1990@gmail.com'
          password: 'SatzTesting@123'
          subject: Playwright Test Report
          to: satz.syk@gmail.com
          from: GitHub CI <your-email@example.com>
          body: Playwright test run completed. See attached report.
          attachments: report.zip
